### ISSUE TITLE
did you update this ?

### ISSUE THREAD

**Issue by ixayldz** [johnathanhowell/openpug#1]
still working ?

**Comment by johnathanhowell** [comment]
No.  I haven't touched this since I stopped working on it over a year ago.

**Comment by ixayldz** [comment]
can you make that  ?

2016-02-16 20:30 GMT+02:00 Johnathan Howell <notifications@github.com>:

**Comment by ixayldz** [comment]
myfriend i search everywhere like this system there is no anything.. but
your idea is very good if u finish this i will like to use.

2016-02-17 10:57 GMT+02:00 isa yıldız <ixayldz@gmail.com>:
